capDesignToGenome:
  HpreCap: shortname
CAPTURE: false
GENOMESDIR: data/fasta/
DATADIR: data/fastq/
produceStatPlots: false
produceTrackHub: false
produceHtmlStatsTable: false
SAMPLE_ANNOT: data/sample_annotations.tsv
sampleRepGroupBy:
  - seqPlatform
  - cellLine
USE_MATCHED_ILLUMINA: false
PROJECT_NAME: shortname_jan
genomeToCAGEpeaks:
  shortname: data/input/fakeCAGE.bed
genomeToAnnotGtf:
  shortname: data/input/Annotation.gtf
genomeToDHSpeaks:
  shortname: data/input/fakeDHS.bed
minimumTmergeReadSupport:
  - "2"
exonOverhangTolerance: "8"
